title: Bio
author: Brandon Wood
email : b.wood@berkeley.edu
github : wood-b

#try permalinks 
permalink: /:categories/:year/:month/:day/:title

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-minimal
